### ISSUE TITLE
Naming of Error types

### ISSUE THREAD

**Issue by krdln** [krdln/whiteread#3]
I'm in the middle of refactoring, which adds a lineinfo for the errors originating from `Reader`.  Let's say we're trying to parse `(i32, i32)` on the 25th line. The `Display` impl produces the following output:

```
excessive input provided at
25| 1 2 3
        ^
```

To achieve that, the error has to store a `&str` or `String` containing a line of text. Creating a `String` on each error is a bad idea (especially if you try to parse a line until there's no error), so I store a `&str`. But that's a borrowed type, which is quite unusable as a return type, so there's also an owned variant storing a `String` with appropriate conversion methods. So we have two error types for a `Reader`.

But there is also underlying `Error` type, which is used directly by a `White` trait and doesn't contain a lineinfo (the lineinfo is added only by a `Reader`).

So there are three error types:
* The "raw" error, currently `white::Error`,
* The borrowed error with lineinfo,
* The owned error with lineinfo,

I'm not happy with that naming, so if you have any thoughts about that, please share them. Maybe @jrmuizel?

The possible solution could be to move the `Reader` into its own module and let it has its own `BorrowedError` and `OwnedError` types, with the owned one reexported as the `ReaderError`.
**Edit** Implemented this solution, and I'm closing the issue for now. If this naming ends up being bad, I'll reopen the issue.

~~~We can also get rid of `BorrowedError` and make it just `&OwnedError`, but that would require the `Reader` to always contain a valid `OwnedError`. Seems ugly and error prone (but provides nicer API).~~~ `io::Error` doesn't implement `Clone`, so it's not really possible to do it.

**Comment by jrmuizel** [comment]
I haven't used any of the error handling yet so I haven't really formed an opinion.
